[project]
name = "TeaPicK"
version = "0.2.1"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "colorlog>=6.9.0",
    "requests>=2.32.5",
    "selenium>=4.39.0",
    "webdriver-manager>=4.0.2",
]
