[user]
username = "your_username"
password = "your_password"

[website]
loginURL = "https://jwxt.sias.edu.cn/eams/loginExt.action"
courseDataURL = "https://jwxt.sias.edu.cn/eams/stdElectCourse!data.action?profileId="
courseSelectURL = "https://jwxt.sias.edu.cn/eams/stdElectCourse!batchOperator.action?profileId="

# 需要改为自己的profileId
profile = 1792

[index-headers]
Connection = "keep-alive"
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
Referer = "https://jwxt.sias.edu.cn/eams/loginExt.action"

[log-config]
LogName = "DebugLog"

[select]
ThreadNum = 8